# Generated by Django 3.1.6 on 2021-02-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20210208_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='author_id',
            new_name='author',
        ),
    ]
